# Exported from Render on 2024-11-27T13:58:02Z
databases:
- name: ServerLess DB
  databaseName: serverless_db_h0mk
  user: steven
  plan: free
  region: frankfurt
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: Servless
  runtime: node
  repo: https://github.com/Sheukn/serverless-al
  plan: free
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: ServerLess DB
      property: connectionString
  region: frankfurt
  buildCommand: npm install
  startCommand: npm start
version: "1"
